version = 5.6.0
archive_dir = /etc/letsencrypt/archive/expiredbread.ru
cert = /etc/letsencrypt/live/expiredbread.ru/cert.pem
privkey = /etc/letsencrypt/live/expiredbread.ru/privkey.pem
chain = /etc/letsencrypt/live/expiredbread.ru/chain.pem
fullchain = /etc/letsencrypt/live/expiredbread.ru/fullchain.pem
[renewalparams]
account = 8f8e6d9a84329b7b4b9513633fba9e06
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
expiredbread.ru = /var/www/certbot
